/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ekzo174 (https://sketchfab.com/Ekzo174)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spray-gun-1fa7191b3e874296909c6817b3d4ed17
Title: Spray Gun
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/spray_gun.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['152_low001_SprayGun_0'].geometry}
        material={materials.SprayGun}
        position={[-0.611, 2.506, 0.249]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['152_low002_SprayGun_0'].geometry}
        material={materials.SprayGun}
        position={[-0.196, 2.692, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['152_low003_SprayGun_0'].geometry}
        material={materials.SprayGun}
        position={[-0.611, 2.506, 0.331]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['152_low004_SprayGun_0'].geometry}
        material={materials.SprayGun}
        position={[0.904, 2.27, 0]}
        rotation={[-1.548, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/spray_gun.glb')